ALTER TABLE "UsageDaily" ADD COLUMN     "cacheReadTokens" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "cacheSavings" DECIMAL(20,10) NOT NULL DEFAULT 0,
ADD COLUMN     "cacheWriteTokens" BIGINT NOT NULL DEFAULT 0;

ALTER TABLE "RequestLog" ADD COLUMN     "cacheReadTokens" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "cacheWriteTokens" INTEGER NOT NULL DEFAULT 0;
